# Generated by Django 4.2 on 2024-09-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='sumary',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='article',
            name='date_pub',
            field=models.DateField(blank=True, null=True),
        ),
    ]
